# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asd2.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 282)
        MainWindow.setStyleSheet("#centralwidget{background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(100, 200, 189, 1), stop:1 rgba(9, 74, 111, 1));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 65, 86);")
        self.label_4.setObjectName("label_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(140, 60, 231, 141))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.login_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.login_lineEdit.setGeometry(QtCore.QRect(100, 20, 113, 20))
        self.login_lineEdit.setStyleSheet("background-color: rgb(229, 240, 255);")
        self.login_lineEdit.setObjectName("login_lineEdit")
        self.pass_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.pass_lineEdit.setGeometry(QtCore.QRect(100, 60, 113, 20))
        self.pass_lineEdit.setStyleSheet("background-color: rgb(229, 240, 255);")
        self.pass_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_lineEdit.setObjectName("pass_lineEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.s_pass_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.s_pass_lineEdit.setGeometry(QtCore.QRect(100, 100, 113, 20))
        self.s_pass_lineEdit.setStyleSheet("background-color: rgb(229, 240, 255);")
        self.s_pass_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.s_pass_lineEdit.setObjectName("s_pass_lineEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 90, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.ca_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ca_btn.setGeometry(QtCore.QRect(190, 220, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ca_btn.setFont(font)
        self.ca_btn.setStyleSheet("background-color: rgb(229, 240, 255);")
        self.ca_btn.setObjectName("ca_btn")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(100, 250, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Create account"))
        self.label_2.setText(_translate("MainWindow", "password"))
        self.label.setText(_translate("MainWindow", "login"))
        self.label_3.setText(_translate("MainWindow", "password"))
        self.label_5.setText(_translate("MainWindow", "confirm"))
        self.ca_btn.setText(_translate("MainWindow", "Create account"))
